{{- if and (eq .Values.githubProxy.enabled true) (eq .Values.ingress.enabled true) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=github
        - --email-domain=*
        - --upstream=http://{{ include "isitup.fullname" . }}.{{.Release.Namespace}}.svc.cluster.local
        - --http-address=0.0.0.0:4180
        - --github-org={{ .Values.githubProxy.githubOrganization }}
        - --pass-basic-auth=false
        - --pass-access-token=false
        # Register a new application
        # https://github.com/settings/applications/new
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: isitup-credentials
              key: github-client-id

        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: isitup-credentials
              key: github-secret

        # docker run -ti --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: NkJ0S08xRE1UanpxT1hTZzZTQ2VVUT09

        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
{{- end }}