apiVersion: v1
kind: Service
metadata:
  name: {{ include "isitup.fullname" . }}
  labels:
    {{- include "isitup.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "isitup.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "isitup.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
